#pragma once

struct EngineData {
    double momentOfInertsia = 10;
    double overheatTemperature = 110;
    double Hm = 0.01;  // Heating rate versus torque coefficient HM
    double Hv =
        0.0001;  // Coefficient of dependence of the heating rate on the speed of rotation of the crankshaft
    double C = 0.1;  // Coefficient of dependence of the cooling rate on the temperature of the engine and
                     // the environment

    // Piecewise linear dependence of the torque generated by the engine on crankshaft speed
    std::vector<double> torque{20, 75, 100, 105, 75, 0};
    std::vector<double> crankshaftSpeed{0, 75, 150, 200, 250, 300};
};